import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Danggeun Market Code */}
        <script src="https://karrot-pixel.business.daangn.com/0.4/karrot-pixel.umd.js"></script>
        <script dangerouslySetInnerHTML={{
          __html: `
            window.karrotPixel.init('1755422197599400001');
            window.karrotPixel.track('ViewPage');
          `
        }} />
        {/* End Danggeun Market Code */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
